export const data = [
  {
    "name": "Photo 1",
    "url": "/images/Photo 1.jpg",
    "description": "Photo 1 description",
    "date": "2020-01-01",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 2",
    "url": "/images/Photo 2.jpg",
    "description": "Photo 2 description",
    "date": "2020-01-02",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 3",
    "url": "/images/Photo 3.jpg",
    "description": "Photo 3 description",
    "date": "2020-01-03",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 4",
    "url": "/images/Photo 4.jpg",
    "description": "Photo 4 description",
    "date": "2020-01-04",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 5",
    "url": "/images/Photo 5.jpg",
    "description": "Photo 5 description",
    "date": "2020-01-05",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 6",
    "url": "/images/Photo 6.jpg",
    "description": "Photo 6 description",
    "date": "2020-01-06",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 7",
    "url": "/images/Photo 7.jpg",
    "description": "Photo 7 description",
    "date": "2020-01-07",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 8",
    "url": "/images/Photo 8.jpg",
    "description": "Photo 8 description",
    "date": "2020-01-08",
    "type": "image/jpeg",
  },
  {
    "name": "Photo 9",
    "url": "/images/Photo 9.jpg",
    "description": "Photo 9 description",
    "date": "2020-01-09",
    "type": "image/jpeg",
  }
]
